name: Deploy QA Kubes at Midnight
# on:
#   schedule:
#     - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
    - name: Checkout main
      uses: actions/checkout@v2
    - name: Deploy Kubes
      run: |
        yarn
        yarn build
        yarn dx profile init \
          --name $WIRE_PROFILE \
          --template-url "$WIRE_PROFILE_URL"
        yarn dx machine delete --name alpha
        # yarn dx machine delete --name beta
        # yarn dx machine delete --name release
        # TODO(telackey): Replace with proper existence check.
        sleep 10
        yarn dx machine create --name alpha --cliver '@alpha' --register
        # yarn dx machine create --name beta --cliver '@beta' --register
        # yarn dx machine create --name release --register
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        WIRE_WNS_USER_KEY: ${{secrets.wns_user_key}}
        WIRE_WNS_BOND_ID: ${{secrets.wns_bond_id}}
        WIRE_PROFILE: ci
        WIRE_PROFILE_URL: ${{secrets.wire_profile_url}}
        WIRE_MACHINE_DO_TOKEN: ${{secrets.wire_machine_do_token}}
        WIRE_MACHINE_GITHUB_TOKEN: ${{secrets.wire_machine_github_token}}
        WIRE_MACHINE_DNS_DOMAIN: ${{secrets.wire_machine_dns_domain}}
